### ISSUE TITLE
Call Stack Bug?

### ISSUE THREAD

**Issue by phoebetse** [elainewlin/MusicBuddy#9]
Error with highlighting text when using motion + speech

`jquery.min.js:2 Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (native)
    at Function.ga [as find] (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:7278)
    at r.fn.init.find (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:24591)
    at r.fn.init (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:25081)
    at r (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:2:601)
    at SongView.that.getChordElement (http://localhost:8000/song.js:44:12)
    at MotionDetect.<anonymous> (http://localhost:8000/setup.js:69:14)
    at MotionDetect.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:3:9922)
    at MotionDetect.q.handle (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:3:7949)`

**Comment by phoebetse** [comment]
Nevermind, fixed (issue was with how Fusion was resetting motion's and speech's currentLines)
